/**
 * Photo Page Builder for ADEQ Inspection PDF
 *
 * Generates photo appendix pages matching the reference layout:
 * - 3 photos per page in card layout with rounded corners
 * - Numbered badges, section labels, dates
 * - Header with address + date, footer with section + page numbers
 * - Uses pdf-lib directly for full layout control
 *
 * Photos are fetched via the signedUrl already present on each MediaRecord
 * (generated by the API using the admin/service-role key).
 */

import {
  PDFDocument,
  StandardFonts,
  rgb,
  type PDFFont,
  type PDFImage,
  type PDFPage,
} from "pdf-lib";
import type { MediaRecord } from "@/components/inspection/media-gallery";
import { STEP_LABELS } from "@/lib/constants/inspection";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface PhotoPageContext {
  address?: string;
  date?: string;
}

// ---------------------------------------------------------------------------
// Layout constants (PDF points, 72pt = 1 inch, US Letter)
// ---------------------------------------------------------------------------

const PAGE_W = 612;
const PAGE_H = 792;
const MARGIN = 40;
const CONTENT_W = PAGE_W - 2 * MARGIN; // 532

// Header
const HEADER_Y = PAGE_H - 38; // 754
const LINE_Y = HEADER_Y - 14; // 740

// Footer
const FOOTER_Y = 26;

// Card grid — 3 cards per page
const CARDS_TOP = LINE_Y - 10; // 730
const CARDS_BOT = FOOTER_Y + 18; // 44
const CARD_GAP = 12;
const CARD_H = Math.floor((CARDS_TOP - CARDS_BOT - 2 * CARD_GAP) / 3); // ~221
const CARD_R = 6;
const CARD_PAD = 10;

// Badge
const BADGE_S = 22;
const BADGE_R = 4;

// Photo area (left side of card)
const PHOTO_W = 248;
const PHOTO_H = CARD_H - 2 * CARD_PAD;

// Metadata area (right side of card)
const META_X = CARD_PAD + PHOTO_W + 16;

// Colors
const C = {
  headerText: rgb(0.42, 0.45, 0.5),
  line: rgb(0.8, 0.84, 0.88),
  cardFill: rgb(0.96, 0.96, 0.97),
  cardBorder: rgb(0.89, 0.89, 0.91),
  badge: rgb(0.39, 0.45, 0.55),
  white: rgb(1, 1, 1),
  dark: rgb(0.22, 0.25, 0.32),
  muted: rgb(0.42, 0.45, 0.5),
  footer: rgb(0.61, 0.64, 0.69),
};

// ---------------------------------------------------------------------------
// Geometry helpers
// ---------------------------------------------------------------------------

/** SVG path for a rounded rectangle (origin at top-left, Y-down for drawSvgPath) */
function rrPath(w: number, h: number, r: number): string {
  const k = 0.5522847498 * r;
  return [
    `M ${r} 0`,
    `L ${w - r} 0`,
    `C ${w - r + k} 0 ${w} ${r - k} ${w} ${r}`,
    `L ${w} ${h - r}`,
    `C ${w} ${h - r + k} ${w - r + k} ${h} ${w - r} ${h}`,
    `L ${r} ${h}`,
    `C ${r - k} ${h} 0 ${h - r + k} 0 ${h - r}`,
    `L 0 ${r}`,
    `C 0 ${r - k} ${r - k} 0 ${r} 0`,
    `Z`,
  ].join(" ");
}

/** Get the Y position (top edge, PDF coords) for a card at the given index (0–2) */
function cardTopY(index: number): number {
  return CARDS_TOP - index * (CARD_H + CARD_GAP);
}

// ---------------------------------------------------------------------------
// Data helpers
// ---------------------------------------------------------------------------

/** Fetch image bytes from a signed URL */
async function fetchImageBytes(
  url: string,
): Promise<{ bytes: Uint8Array; isPng: boolean } | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const buf = await res.arrayBuffer();
    const bytes = new Uint8Array(buf);
    const isPng =
      bytes.length > 4 &&
      bytes[0] === 0x89 &&
      bytes[1] === 0x50 &&
      bytes[2] === 0x4e &&
      bytes[3] === 0x47;
    return { bytes, isPng };
  } catch {
    return null;
  }
}

/** Format ISO date to "Mar 2, 2026, 9:35 PM" */
function fmtDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    });
  } catch {
    return iso;
  }
}

/** Format date for the page header — "Mar 2, 2026" */
function fmtHeaderDate(date?: string): string {
  const d = date ? new Date(date) : new Date();
  try {
    return d.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return date ?? "";
  }
}

// ---------------------------------------------------------------------------
// Photo grouping
// ---------------------------------------------------------------------------

interface PhotoGroup {
  sectionLabel: string;
  photos: MediaRecord[];
}

function groupPhotosBySection(photos: MediaRecord[]): PhotoGroup[] {
  const map = new Map<string, MediaRecord[]>();
  for (const p of photos) {
    const key = p.label ?? "Other";
    const arr = map.get(key) ?? [];
    arr.push(p);
    map.set(key, arr);
  }
  const ordered: PhotoGroup[] = [];
  for (const label of STEP_LABELS) {
    const group = map.get(label);
    if (group?.length) {
      ordered.push({ sectionLabel: label, photos: group });
      map.delete(label);
    }
  }
  for (const [label, group] of map) {
    if (group.length) ordered.push({ sectionLabel: label, photos: group });
  }
  return ordered;
}

// ---------------------------------------------------------------------------
// Drawing functions
// ---------------------------------------------------------------------------

interface Fonts {
  regular: PDFFont;
  bold: PDFFont;
}

function drawHeader(page: PDFPage, fonts: Fonts, address: string, date: string) {
  page.drawText(address, {
    x: MARGIN,
    y: HEADER_Y,
    size: 10,
    font: fonts.regular,
    color: C.muted,
  });
  const dw = fonts.regular.widthOfTextAtSize(date, 10);
  page.drawText(date, {
    x: PAGE_W - MARGIN - dw,
    y: HEADER_Y,
    size: 10,
    font: fonts.regular,
    color: C.muted,
  });
  page.drawLine({
    start: { x: MARGIN - 2, y: LINE_Y },
    end: { x: PAGE_W - MARGIN + 2, y: LINE_Y },
    thickness: 0.75,
    color: C.line,
  });
}

function drawFooter(
  page: PDFPage,
  fonts: Fonts,
  sectionLabel: string,
  pageNum: number,
  totalPages: number,
) {
  page.drawText(sectionLabel, {
    x: MARGIN,
    y: FOOTER_Y,
    size: 9,
    font: fonts.regular,
    color: C.footer,
  });
  const pt = `${pageNum} / ${totalPages}`;
  const ptw = fonts.regular.widthOfTextAtSize(pt, 9);
  page.drawText(pt, {
    x: (PAGE_W - ptw) / 2,
    y: FOOTER_Y,
    size: 9,
    font: fonts.regular,
    color: C.footer,
  });
  const rt = "Inspection Photos";
  const rtw = fonts.regular.widthOfTextAtSize(rt, 9);
  page.drawText(rt, {
    x: PAGE_W - MARGIN - rtw,
    y: FOOTER_Y,
    size: 9,
    font: fonts.regular,
    color: C.footer,
  });
}

function drawCardBg(page: PDFPage, top: number) {
  page.drawSvgPath(rrPath(CONTENT_W, CARD_H, CARD_R), {
    x: MARGIN,
    y: top,
    color: C.cardFill,
    borderColor: C.cardBorder,
    borderWidth: 0.75,
  });
}

function drawBadge(page: PDFPage, font: PDFFont, top: number, num: number) {
  const bx = MARGIN + 8;
  const by = top - 8;
  page.drawSvgPath(rrPath(BADGE_S, BADGE_S, BADGE_R), {
    x: bx,
    y: by,
    color: C.badge,
  });
  const text = String(num);
  const tw = font.widthOfTextAtSize(text, 11);
  // Text baseline inside badge — drawSvgPath places y at top, badge extends down
  page.drawText(text, {
    x: bx + (BADGE_S - tw) / 2,
    y: by - BADGE_S + 7,
    size: 11,
    font,
    color: C.white,
  });
}

function drawPhotoImage(page: PDFPage, image: PDFImage, cTop: number) {
  const areaX = MARGIN + CARD_PAD;
  const areaBot = cTop - CARD_H + CARD_PAD;
  const areaW = PHOTO_W;
  const areaH = PHOTO_H;

  const imgAspect = image.width / image.height;
  const areaAspect = areaW / areaH;
  let drawW: number;
  let drawH: number;
  if (imgAspect > areaAspect) {
    drawW = areaW;
    drawH = areaW / imgAspect;
  } else {
    drawH = areaH;
    drawW = areaH * imgAspect;
  }

  page.drawImage(image, {
    x: areaX + (areaW - drawW) / 2,
    y: areaBot + (areaH - drawH) / 2,
    width: drawW,
    height: drawH,
  });
}

function drawMetadata(
  page: PDFPage,
  fonts: Fonts,
  cTop: number,
  description: string | null | undefined,
  createdAt: string,
  photoNum: number,
  totalPhotos: number,
) {
  const metaX = MARGIN + META_X;
  const mid = cTop - CARD_H / 2;
  const lineH = 18;

  // Description (bold) — only shown if user provided one
  if (description) {
    page.drawText(description, {
      x: metaX,
      y: mid + lineH + 4,
      size: 11,
      font: fonts.bold,
      color: C.dark,
      maxWidth: CONTENT_W - META_X - CARD_PAD,
    });
  }

  // Date
  page.drawText(`Date:  ${fmtDate(createdAt)}`, {
    x: metaX,
    y: mid - 4,
    size: 10,
    font: fonts.regular,
    color: C.muted,
  });

  // Photo number
  page.drawText(`Photo ${photoNum} of ${totalPhotos}`, {
    x: metaX,
    y: mid - lineH - 4,
    size: 10,
    font: fonts.regular,
    color: C.muted,
  });
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Builds photo appendix pages for the ADEQ inspection PDF.
 *
 * @param media - All media records for the inspection (photos + videos)
 * @param context - Optional address/date to display in the page header
 * @returns Uint8Array PDF of photo pages, or null if no photos
 */
export async function buildPhotoPages(
  media: MediaRecord[],
  context?: PhotoPageContext,
): Promise<Uint8Array | null> {
  const photos = media.filter((m) => m.type === "photo");
  if (photos.length === 0) return null;

  // Group by section and flatten into ordered list
  const groups = groupPhotosBySection(photos);
  interface Entry {
    photo: MediaRecord;
    sectionLabel: string;
    globalIdx: number;
  }
  const entries: Entry[] = [];
  for (const g of groups) {
    for (const p of g.photos) {
      entries.push({ photo: p, sectionLabel: g.sectionLabel, globalIdx: entries.length });
    }
  }
  if (entries.length === 0) return null;

  // Fetch all photo bytes in parallel (using signedUrl from MediaRecord)
  const rawMap = new Map<string, { bytes: Uint8Array; isPng: boolean }>();
  await Promise.all(
    entries.map(async ({ photo }) => {
      if (!photo.signedUrl) return;
      const data = await fetchImageBytes(photo.signedUrl);
      if (data) rawMap.set(photo.id, data);
    }),
  );

  // Create the PDF document and embed fonts
  const doc = await PDFDocument.create();
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const fonts: Fonts = { regular, bold };

  // Embed all fetched images into the document
  const imageMap = new Map<string, PDFImage>();
  for (const [id, data] of rawMap) {
    try {
      const img = data.isPng
        ? await doc.embedPng(data.bytes)
        : await doc.embedJpg(data.bytes);
      imageMap.set(id, img);
    } catch (err) {
      console.error(`Failed to embed photo ${id}:`, err);
    }
  }

  // If no images were successfully embedded, bail
  if (imageMap.size === 0) return null;

  // Header info
  const headerAddress = context?.address || "Inspection Photos";
  const headerDate = fmtHeaderDate(context?.date);
  const totalPhotos = entries.length;
  const perPage = 3;
  const totalPages = Math.ceil(totalPhotos / perPage);

  // Build pages
  for (let pi = 0; pi < totalPages; pi++) {
    const page = doc.addPage([PAGE_W, PAGE_H]);
    const pageEntries = entries.slice(pi * perPage, (pi + 1) * perPage);
    const footerSection = pageEntries[0]?.sectionLabel ?? "Photos";

    drawHeader(page, fonts, headerAddress, headerDate);
    drawFooter(page, fonts, footerSection, pi + 1, totalPages);

    for (let ci = 0; ci < pageEntries.length; ci++) {
      const { photo, sectionLabel, globalIdx } = pageEntries[ci];
      const cTop = cardTopY(ci);

      drawCardBg(page, cTop);
      drawBadge(page, bold, cTop, globalIdx + 1);

      const img = imageMap.get(photo.id);
      if (img) {
        drawPhotoImage(page, img, cTop);
      }

      drawMetadata(page, fonts, cTop, photo.description, photo.createdAt, globalIdx + 1, totalPhotos);
    }
  }

  const pdfBytes = await doc.save();
  return new Uint8Array(pdfBytes);
}
